name: Lint

on:
  push:
    branches-ignore: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    -
      name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    -
      name: Clone repository
      uses: actions/checkout@v4
    -
      name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: -v --timeout=5m
        skip-build-cache: true
        skip-go-installation: true
        skip-pkg-cache: true
