name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    -
      name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    -
      name: Clone repository
      uses: actions/checkout@v4
    -
      name: Test
      run: make test
